import type { Routine } from './types'

// All exerciseId values verified against public/exercises.json via
// `jq -r '.[].id' src/frontend/public/exercises.json`.
//
// Stable string ids (not random) so re-renders are stable and tests can
// pin them; createdAt: 0 keeps starters sorting before user-created ones
// when sorting by createdAt ascending.

export const STARTER_ROUTINES: Routine[] = [
  // ── Original 6 generic starters (Phase 2) ─────────────────────────────────
  {
    id: 'starter-beginner-full-body',
    name: 'Beginner Full Body',
    isStarter: true,
    sport: 'general',
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Bodyweight_Squat', sets: 3, reps: '12', restSeconds: 60 },
      { exerciseId: 'Pushups', sets: 3, reps: '10', restSeconds: 60 },
      { exerciseId: 'Inverted_Row', sets: 3, reps: '10', restSeconds: 60 },
      { exerciseId: 'Plank', sets: 3, reps: '30s', restSeconds: 45 },
      { exerciseId: 'Butt_Lift_Bridge', sets: 3, reps: '12', restSeconds: 45 },
    ],
  },
  {
    id: 'starter-upper-body-push',
    name: 'Upper Body Push',
    isStarter: true,
    sport: 'general',
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Pushups', sets: 4, reps: '8-12', restSeconds: 90 },
      { exerciseId: 'Dumbbell_Shoulder_Press', sets: 4, reps: '8-10', restSeconds: 90 },
      { exerciseId: 'Bench_Dips', sets: 3, reps: '10', restSeconds: 60 },
      { exerciseId: 'Side_Lateral_Raise', sets: 3, reps: '12', restSeconds: 45 },
    ],
  },
  {
    id: 'starter-upper-body-pull',
    name: 'Upper Body Pull',
    isStarter: true,
    sport: 'general',
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Pullups', sets: 4, reps: '6-10', restSeconds: 90 },
      { exerciseId: 'Dumbbell_Bicep_Curl', sets: 3, reps: '12', restSeconds: 60 },
      { exerciseId: 'Face_Pull', sets: 3, reps: '15', restSeconds: 45 },
    ],
  },
  {
    id: 'starter-lower-body',
    name: 'Lower Body',
    isStarter: true,
    sport: 'general',
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Goblet_Squat', sets: 4, reps: '10', restSeconds: 90 },
      { exerciseId: 'Dumbbell_Lunges', sets: 3, reps: '10 each leg', restSeconds: 60 },
      { exerciseId: 'Romanian_Deadlift', sets: 3, reps: '8-10', restSeconds: 90 },
      { exerciseId: 'Standing_Calf_Raises', sets: 3, reps: '15', restSeconds: 30 },
    ],
  },
  {
    id: 'starter-core-crusher',
    name: 'Core Crusher',
    isStarter: true,
    sport: 'general',
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Plank', sets: 3, reps: '45s', restSeconds: 45 },
      { exerciseId: 'Russian_Twist', sets: 3, reps: '20', restSeconds: 30 },
      { exerciseId: 'Dead_Bug', sets: 3, reps: '10 each side', restSeconds: 30 },
      { exerciseId: 'Flat_Bench_Lying_Leg_Raise', sets: 3, reps: '12', restSeconds: 45 },
    ],
  },
  {
    id: 'starter-mobility',
    name: '5-Minute Mobility',
    isStarter: true,
    sport: 'general',
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Cat_Stretch', sets: 1, reps: '60s', restSeconds: 0 },
      { exerciseId: 'Worlds_Greatest_Stretch', sets: 1, reps: '30s each side', restSeconds: 0 },
      { exerciseId: 'Hamstring_Stretch', sets: 1, reps: '30s each leg', restSeconds: 0 },
      { exerciseId: 'Arm_Circles', sets: 1, reps: '60s', restSeconds: 0 },
    ],
  },

  // ── Climbing (4 routines, issue #35) ──────────────────────────────────────
  {
    id: 'starter-climbing-max-pull',
    name: 'Climbing — Max Pulling Strength',
    isStarter: true,
    sport: 'climbing',
    level: 'intermediate',
    tags: ['pull', 'strength'],
    description: 'Heavy pulling work to raise your ceiling for hard climbing moves.',
    source: { label: 'Hörst, Training for Climbing' },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Scapular_Pull-Up', sets: 3, reps: '5', restSeconds: 60 },
      { exerciseId: 'Pullups', sets: 5, reps: '5', restSeconds: 180 },
      { exerciseId: 'Chin-Up', sets: 4, reps: '6', restSeconds: 120 },
      { exerciseId: 'Inverted_Row', sets: 3, reps: '8', restSeconds: 90 },
      { exerciseId: 'Hanging_Leg_Raise', sets: 3, reps: '8', restSeconds: 60 },
    ],
  },
  {
    id: 'starter-climbing-antagonist',
    name: 'Climbing — Antagonist & Recovery',
    isStarter: true,
    sport: 'climbing',
    level: 'beginner',
    tags: ['antagonist', 'mobility', 'recovery'],
    description: 'Balance pulling-heavy climbing with pressing + forearm health.',
    source: { label: 'Lattice Training blog', url: 'https://latticetraining.com/blog/' },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Pushups', sets: 3, reps: '12', restSeconds: 60 },
      { exerciseId: 'Bench_Dips', sets: 3, reps: '10', restSeconds: 60 },
      { exerciseId: 'Handstand_Push-Ups', sets: 3, reps: '5', restSeconds: 90 },
      { exerciseId: 'Finger_Curls', sets: 3, reps: '15', restSeconds: 45 },
      { exerciseId: 'Kneeling_Forearm_Stretch', sets: 1, reps: '60s each side', restSeconds: 0 },
      { exerciseId: 'Worlds_Greatest_Stretch', sets: 1, reps: '30s each side', restSeconds: 0 },
      { exerciseId: 'Childs_Pose', sets: 1, reps: '60s', restSeconds: 0 },
    ],
  },
  {
    id: 'starter-climbing-power-endurance',
    name: 'Climbing — Power Endurance',
    isStarter: true,
    sport: 'climbing',
    level: 'intermediate',
    tags: ['endurance', 'pull'],
    description: 'Sustain pulling power across longer sequences.',
    source: { label: 'Bechtel, Logical Progression' },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Pullups', sets: 3, reps: 'max-2', restSeconds: 180 },
      { exerciseId: 'Bent_Over_Two-Dumbbell_Row', sets: 3, reps: '10', restSeconds: 90 },
      { exerciseId: 'Hanging_Pike', sets: 3, reps: '8', restSeconds: 60 },
      { exerciseId: 'Mountain_Climbers', sets: 3, reps: '30s', restSeconds: 30 },
      { exerciseId: 'Plank', sets: 3, reps: '60s', restSeconds: 45 },
    ],
  },
  {
    id: 'starter-climbing-core',
    name: 'Climbing — Core for Climbers',
    isStarter: true,
    sport: 'climbing',
    level: 'beginner',
    tags: ['core'],
    description: 'Climbing-specific core circuit emphasizing tension and hip drive.',
    source: { label: 'General climbing canon' },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Hanging_Leg_Raise', sets: 3, reps: '8', restSeconds: 60 },
      { exerciseId: 'Hanging_Pike', sets: 3, reps: '8', restSeconds: 60 },
      { exerciseId: 'Plank', sets: 3, reps: '45s', restSeconds: 30 },
      { exerciseId: 'Side_Bridge', sets: 3, reps: '30s each side', restSeconds: 30 },
      { exerciseId: 'Russian_Twist', sets: 3, reps: '20', restSeconds: 30 },
      { exerciseId: 'Dead_Bug', sets: 3, reps: '10 each side', restSeconds: 30 },
    ],
  },

  // ── Calisthenics (5 routines, issue #35) ─────────────────────────────────
  {
    id: 'starter-calisthenics-starting-strength',
    name: 'Calisthenics — Starting Strength',
    isStarter: true,
    sport: 'calisthenics',
    level: 'beginner',
    tags: ['full-body', 'strength'],
    description: 'Recommended-Routine-style full-body template for new lifters.',
    source: {
      label: 'r/bodyweightfitness Recommended Routine',
      url: 'https://www.reddit.com/r/bodyweightfitness/wiki/kb/recommended_routine',
    },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Bodyweight_Squat', sets: 3, reps: '12', restSeconds: 90 },
      { exerciseId: 'Pushups', sets: 3, reps: '8', restSeconds: 90 },
      { exerciseId: 'Inverted_Row', sets: 3, reps: '8', restSeconds: 90 },
      { exerciseId: 'Glute_Ham_Raise', sets: 3, reps: '5', restSeconds: 90 },
      { exerciseId: 'Plank', sets: 3, reps: '30s', restSeconds: 30 },
      { exerciseId: 'Hanging_Leg_Raise', sets: 3, reps: '6', restSeconds: 60 },
    ],
  },
  {
    id: 'starter-calisthenics-push',
    name: 'Calisthenics — Push Strength',
    isStarter: true,
    sport: 'calisthenics',
    level: 'intermediate',
    tags: ['push', 'strength'],
    description: 'Pressing volume + variation for chest, shoulders, and triceps.',
    source: { label: 'GMB Elements', url: 'https://gmb.io/elements/' },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Pushups', sets: 4, reps: '8-12', restSeconds: 90 },
      { exerciseId: 'Decline_Push-Up', sets: 4, reps: '8', restSeconds: 120 },
      { exerciseId: 'Close-Grip_Push-Up_off_of_a_Dumbbell', sets: 3, reps: '8', restSeconds: 90 },
      { exerciseId: 'Bench_Dips', sets: 3, reps: '10', restSeconds: 60 },
      { exerciseId: 'Handstand_Push-Ups', sets: 3, reps: '3-5', restSeconds: 120 },
    ],
  },
  {
    id: 'starter-calisthenics-pull',
    name: 'Calisthenics — Pull Strength',
    isStarter: true,
    sport: 'calisthenics',
    level: 'intermediate',
    tags: ['pull', 'strength'],
    description: 'Heavy bar work: pull-ups, chin-ups, rows.',
    source: { label: 'r/bodyweightfitness Move', url: 'https://www.reddit.com/r/bodyweightfitness/' },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Scapular_Pull-Up', sets: 3, reps: '5', restSeconds: 60 },
      { exerciseId: 'Pullups', sets: 5, reps: '5', restSeconds: 180 },
      { exerciseId: 'Chin-Up', sets: 4, reps: '6', restSeconds: 120 },
      { exerciseId: 'Inverted_Row', sets: 3, reps: '8', restSeconds: 90 },
      { exerciseId: 'Hanging_Leg_Raise', sets: 3, reps: '8', restSeconds: 60 },
    ],
  },
  {
    id: 'starter-calisthenics-lower',
    name: 'Calisthenics — Single-Leg & Lower',
    isStarter: true,
    sport: 'calisthenics',
    level: 'intermediate',
    tags: ['legs', 'unilateral'],
    description: 'Unilateral lower-body work for balanced strength and mobility.',
    source: { label: 'Convict Conditioning progressions' },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Bodyweight_Squat', sets: 3, reps: '15', restSeconds: 60 },
      { exerciseId: 'Kettlebell_Pistol_Squat', sets: 4, reps: '5 each leg', restSeconds: 90 },
      { exerciseId: 'Dumbbell_Lunges', sets: 3, reps: '10 each leg', restSeconds: 60 },
      { exerciseId: 'Single_Leg_Glute_Bridge', sets: 3, reps: '10 each side', restSeconds: 45 },
      { exerciseId: 'Standing_Calf_Raises', sets: 3, reps: '15', restSeconds: 30 },
    ],
  },
  {
    id: 'starter-calisthenics-skill',
    name: 'Calisthenics — Skill & Conditioning',
    isStarter: true,
    sport: 'calisthenics',
    level: 'advanced',
    tags: ['skill', 'conditioning'],
    description: 'High-skill work plus a conditioning finisher.',
    source: { label: 'GMB Foundations', url: 'https://gmb.io/foundations/' },
    createdAt: 0,
    updatedAt: 0,
    exercises: [
      { exerciseId: 'Handstand_Push-Ups', sets: 4, reps: '3', restSeconds: 120 },
      { exerciseId: 'One_Arm_Chin-Up', sets: 3, reps: '3 each arm', restSeconds: 180 },
      { exerciseId: 'Hanging_Pike', sets: 3, reps: '8', restSeconds: 90 },
      { exerciseId: 'Pushups', sets: 3, reps: 'max', restSeconds: 60 },
      { exerciseId: 'Mountain_Climbers', sets: 3, reps: '30s', restSeconds: 30 },
    ],
  },
]
